### ISSUE TITLE
Get rid of rvm

### ISSUE THREAD

**Issue by haihappen** [Folis/revmoji#1]
Hello @Folis,

just a simple suggestion: I wouldn't recommend installing rvm. Here a few reasons:
* rvm's fanbase is shrinking because of [rbenv](https://github.com/sstephenson/rbenv/wiki/Why-rbenv%3F).
* Production systems shouldn't have more than one ruby version installed. 
* OS X comes already with ruby installed. ;)

**Comment by Folis** [comment]
Yo,
 
see f6b8b32ea23c4065e4ab37de4564510c449003a7 for the "fix". I swear getting rid of rvm is pretty nasty. But now that's done!
